name: RPChecker Build

on:
  push:
    branches: github-actions

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Restore Packages
      run: nuget restore RPChecker.sln

    - name: Build Solution
      run: |
        msbuild.exe RPChecker.sln /nologo /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release"

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: RPChecker-release
        path: "./RPChecker/bin/"
